;#################################################
; Blitz3D SDK Interface for PureBasic 4.0
; 04.08.07
; by Platon www.freeloopsoftware.yahoo.com
; //Enchanced in 2011 by Guevara-chan.
; Use at your own risk!
;#################################################

Global B3DLibrary = OpenLibrary(#PB_Any, "DLL\B3D.dll")
PrototypeC.l _Version()
Global Version_._Version = GetFunction(B3DLibrary, "bbVersion")
PrototypeC.l _SetBlitz3DDebugMode(Mode.l)
Global SetBlitz3DDebugMode_._SetBlitz3DDebugMode = GetFunction(B3DLibrary, "bbSetBlitz3DDebugMode")
PrototypeC.l _SetBlitz3DDebugCallback(*Callback)
Global SetBlitz3DDebugCallback_._SetBlitz3DDebugCallback = GetFunction(B3DLibrary, "bbSetBlitz3DDebugCallback")
PrototypeC.l _SetBlitz3DEventCallback(*Callback)
Global SetBlitz3DEventCallback_._SetBlitz3DEventCallback = GetFunction(B3DLibrary, "bbSetBlitz3DEventCallback")
PrototypeC.l _SetBlitz3DHWND(Parent.l)
Global SetBlitz3DHWND_._SetBlitz3DHWND = GetFunction(B3DLibrary, "bbSetBlitz3DHWND")
PrototypeC.l _SetBlitz3DTitle(Title.p-ascii, CloseMsg.p-ascii)
Global SetBlitz3DTitle_._SetBlitz3DTitle = GetFunction(B3DLibrary, "bbSetBlitz3DTitle")
PrototypeC.l _BeginBlitz3D()
Global BeginBlitz3D_._BeginBlitz3D = GetFunction(B3DLibrary, "bbBeginBlitz3D")
PrototypeC.l _EndBlitz3D()
Global EndBlitz3D_._EndBlitz3D = GetFunction(B3DLibrary, "bbEndBlitz3D")
PrototypeC _RuntimeError(ErrorMsg.p-ascii)
Global RuntimeError_._RuntimeError = GetFunction(B3DLibrary, "bbRuntimeError")
PrototypeC.l _MilliSecs()
Global MilliSecs_._MilliSecs = GetFunction(B3DLibrary, "bbMilliSecs")
PrototypeC _Delay(Time.l)
Global Delay_._Delay = GetFunction(B3DLibrary, "bbDelay")
PrototypeC _ShowPointer()
Global ShowPointer_._ShowPointer = GetFunction(B3DLibrary, "bbShowPointer")
PrototypeC _HidePointer()
Global HidePointer_._HidePointer = GetFunction(B3DLibrary, "bbHidePointer")
PrototypeC.l _CreateTimer(Frequency.l)
Global CreateTimer_._CreateTimer = GetFunction(B3DLibrary, "bbCreateTimer")
PrototypeC _FreeTimer(Timer.l)
Global FreeTimer_._FreeTimer = GetFunction(B3DLibrary, "bbFreeTimer")
PrototypeC _WaitTimer(Timer.l)
Global WaitTimer_._WaitTimer = GetFunction(B3DLibrary, "bbWaitTimer")
PrototypeC.l _KeyDown(Key.l)
Global KeyDown_._KeyDown = GetFunction(B3DLibrary, "bbKeyDown")
PrototypeC.l _KeyHit(Key.l)
Global KeyHit_._KeyHit = GetFunction(B3DLibrary, "bbKeyHit")
PrototypeC.l _GetKey()
Global GetKey_._GetKey = GetFunction(B3DLibrary, "bbGetKey")
PrototypeC.l _WaitKey()
Global WaitKey_._WaitKey = GetFunction(B3DLibrary, "bbWaitKey")
PrototypeC _FlushKeys()
Global FlushKeys_._FlushKeys = GetFunction(B3DLibrary, "bbFlushKeys")
PrototypeC.l _MouseDown(Key.l)
Global MouseDown_._MouseDown = GetFunction(B3DLibrary, "bbMouseDown")
PrototypeC.l _MouseHit(Key.l)
Global MouseHit_._MouseHit = GetFunction(B3DLibrary, "bbMouseHit")
PrototypeC.l _GetMouse()
Global GetMouse_._GetMouse = GetFunction(B3DLibrary, "bbGetMouse")
PrototypeC.l _WaitMouse()
Global WaitMouse_._WaitMouse = GetFunction(B3DLibrary, "bbWaitMouse")
PrototypeC.l _MouseX()
Global MouseX_._MouseX = GetFunction(B3DLibrary, "bbMouseX")
PrototypeC.l _MouseY()
Global MouseY_._MouseY = GetFunction(B3DLibrary, "bbMouseY")
PrototypeC.l _MouseZ()
Global MouseZ_._MouseZ = GetFunction(B3DLibrary, "bbMouseZ")
PrototypeC.l _MouseXSpeed()
Global MouseXSpeed_._MouseXSpeed = GetFunction(B3DLibrary, "bbMouseXSpeed")
PrototypeC.l _MouseYSpeed()
Global MouseYSpeed_._MouseYSpeed = GetFunction(B3DLibrary, "bbMouseYSpeed")
PrototypeC.l _MouseZSpeed()
Global MouseZSpeed_._MouseZSpeed = GetFunction(B3DLibrary, "bbMouseZSpeed")
PrototypeC _MoveMouse(x.l, y.l)
Global MoveMouse_._MoveMouse = GetFunction(B3DLibrary, "bbMoveMouse")
PrototypeC _FlushMouse()
Global FlushMouse_._FlushMouse = GetFunction(B3DLibrary, "bbFlushMouse")
PrototypeC.l _JoyType(Port.l = 0)
Global JoyType_._JoyType = GetFunction(B3DLibrary, "bbJoyType")
PrototypeC.l _JoyDown(Key.l, Port.l = 0)
Global JoyDown_._JoyDown = GetFunction(B3DLibrary, "bbJoyDown")
PrototypeC.l _JoyHit(Key.l, Port.l = 0)
Global JoyHit_._JoyHit = GetFunction(B3DLibrary, "bbJoyHit")
PrototypeC.l _GetJoy(Port.l = 0)
Global GetJoy_._GetJoy = GetFunction(B3DLibrary, "bbGetJoy")
PrototypeC.l _WaitJoy(Port.l = 0)
Global WaitJoy_._WaitJoy = GetFunction(B3DLibrary, "bbWaitJoy")
PrototypeC.f _JoyX(Port.l = 0)
Global JoyX_._JoyX = GetFunction(B3DLibrary, "bbJoyX")
PrototypeC.f _JoyY(Port.l = 0)
Global JoyY_._JoyY = GetFunction(B3DLibrary, "bbJoyY")
PrototypeC.f _JoyZ(Port.l = 0)
Global JoyZ_._JoyZ = GetFunction(B3DLibrary, "bbJoyZ")
PrototypeC.f _JoyU(Port.l = 0)
Global JoyU_._JoyU = GetFunction(B3DLibrary, "bbJoyU")
PrototypeC.f _JoyV(Port.l = 0)
Global JoyV_._JoyV = GetFunction(B3DLibrary, "bbJoyV")
PrototypeC.f _JoyPitch(Port.l = 0)
Global JoyPitch_._JoyPitch = GetFunction(B3DLibrary, "bbJoyPitch")
PrototypeC.f _JoyYaw(Port.l = 0)
Global JoyYaw_._JoyYaw = GetFunction(B3DLibrary, "bbJoyYaw")
PrototypeC.f _JoyRoll(Port.l = 0)
Global JoyRoll_._JoyRoll = GetFunction(B3DLibrary, "bbJoyRoll")
PrototypeC.l _JoyHat(Port.l = 0)
Global JoyHat_._JoyHat = GetFunction(B3DLibrary, "bbJoyHat")
PrototypeC.l _JoyXDir(Port.l = 0)
Global JoyXDir_._JoyXDir = GetFunction(B3DLibrary, "bbJoyXDir")
PrototypeC.l _JoyYDir(Port.l = 0)
Global JoyYDir_._JoyYDir = GetFunction(B3DLibrary, "bbJoyYDir")
PrototypeC.l _JoyZDir(Port.l = 0)
Global JoyZDir_._JoyZDir = GetFunction(B3DLibrary, "bbJoyZDir")
PrototypeC.l _JoyUDir(Port.l = 0)
Global JoyUDir_._JoyUDir = GetFunction(B3DLibrary, "bbJoyUDir")
PrototypeC.l _JoyVDir(Port.l = 0)
Global JoyVDir_._JoyVDir = GetFunction(B3DLibrary, "bbJoyVDir")
PrototypeC _FlushJoy()
Global FlushJoy_._FlushJoy = GetFunction(B3DLibrary, "bbFlushJoy")
PrototypeC.l _LoadSound(Filename.p-ascii, Flags.l = 0)
Global LoadSound_._LoadSound = GetFunction(B3DLibrary, "bbLoadSound")
PrototypeC _FreeSound(Sound.l)
Global FreeSound_._FreeSound = GetFunction(B3DLibrary, "bbFreeSound")
PrototypeC _PlaySound(Sound.l)
Global PlaySound_._PlaySound = GetFunction(B3DLibrary, "bbPlaySound")
PrototypeC _LoopSound(Sound.l)
Global LoopSound_._LoopSound = GetFunction(B3DLibrary, "bbLoopSound")
PrototypeC _SoundPitch(Sound.l, Pitch.l)
Global SoundPitch_._SoundPitch = GetFunction(B3DLibrary, "bbSoundPitch")
PrototypeC _SoundVolume(Sound.l, Volume.f)
Global SoundVolume_._SoundVolume = GetFunction(B3DLibrary, "bbSoundVolume")
PrototypeC _SoundPan(Sound.l, Pan.f)
Global SoundPan_._SoundPan = GetFunction(B3DLibrary, "bbSoundPan")
PrototypeC.l _PlayMusic(Filename.p-ascii, Mode.l = 1)
Global PlayMusic_._PlayMusic = GetFunction(B3DLibrary, "bbPlayMusic")
PrototypeC.l _PlayCDTrack(Track.l, Mode.l = 1)
Global PlayCDTrack_._PlayCDTrack = GetFunction(B3DLibrary, "bbPlayCDTrack")
PrototypeC _StopChannel(Channel.l)
Global StopChannel_._StopChannel = GetFunction(B3DLibrary, "bbStopChannel")
PrototypeC _PauseChannel(Channel.l)
Global PauseChannel_._PauseChannel = GetFunction(B3DLibrary, "bbPauseChannel")
PrototypeC _ResumeChannel(Channel.l)
Global ResumeChannel_._ResumeChannel = GetFunction(B3DLibrary, "bbResumeChannel")
PrototypeC _ChannelPitch(Channel.l, Pitch.l)
Global ChannelPitch_._ChannelPitch = GetFunction(B3DLibrary, "bbChannelPitch")
PrototypeC _ChannelVolume(Channel.l, Volume.f)
Global ChannelVolume_._ChannelVolume = GetFunction(B3DLibrary, "bbChannelVolume")
PrototypeC _ChannelPan(Channel.l, Pan.f)
Global ChannelPan_._ChannelPan = GetFunction(B3DLibrary, "bbChannelPan")
PrototypeC.l _ChannelPlaying(Channel.l)
Global ChannelPlaying_._ChannelPlaying = GetFunction(B3DLibrary, "bbChannelPlaying")
PrototypeC _Graphics3D(Width.l, Height.l, Depth.l = 0, Mode.l = 0)
Global Graphics3D_._Graphics3D = GetFunction(B3DLibrary, "bbGraphics3D")
PrototypeC.l _CountGfxDrivers()
Global CountGfxDrivers_._CountGfxDrivers = GetFunction(B3DLibrary, "bbCountGfxDrivers")
PrototypeC.l _GfxDriverName(Driver.l)
Global _GfxDriverName_._GfxDriverName = GetFunction(B3DLibrary, "bbGfxDriverName")
Macro GfxDriverName_(Driver) : PeekS(_GfxDriverName_(Driver), -1, #PB_Ascii) : EndMacro
PrototypeC.l _GfxDriver3D(Driver.l)
Global GfxDriver3D_._GfxDriver3D = GetFunction(B3DLibrary, "bbGfxDriver3D")
PrototypeC.l _GfxDriverCaps3D()
Global GfxDriverCaps3D_._GfxDriverCaps3D = GetFunction(B3DLibrary, "bbGfxDriverCaps3D")
PrototypeC.l _CountGfxModes3D()
Global CountGfxModes3D_._CountGfxModes3D = GetFunction(B3DLibrary, "bbCountGfxModes3D")
PrototypeC.l _GfxMode3DExists(Width.l, Height.l, Depth.l)
Global GfxMode3DExists_._GfxMode3DExists = GetFunction(B3DLibrary, "bbGfxMode3DExists")
PrototypeC.l _GfxMode3D(Mode.l)
Global GfxMode3D_._GfxMode3D = GetFunction(B3DLibrary, "bbGfxMode3D")
PrototypeC.l _Windowed3D()
Global Windowed3D_._Windowed3D = GetFunction(B3DLibrary, "bbWindowed3D")
PrototypeC.l _GfxDriverX(Driver.l)
Global GfxDriverX_._GfxDriverX = GetFunction(B3DLibrary, "bbGfxDriverX")
PrototypeC.l _GfxDriverY(Driver.l)
Global GfxDriverY_._GfxDriverY = GetFunction(B3DLibrary, "bbGfxDriverY")
PrototypeC.l _GfxDriverHz(Driver.l)
Global GfxDriverHz_._GfxDriverHz = GetFunction(B3DLibrary, "bbGfxDriverHz")
PrototypeC _SetGfxDriver(Driver.l)
Global SetGfxDriver_._SetGfxDriver = GetFunction(B3DLibrary, "bbSetGfxDriver")
PrototypeC.l _GfxModeExists(Width.l, Height.l, Depth.l)
Global GfxModeExists_._GfxModeExists = GetFunction(B3DLibrary, "bbGfxModeExists")
PrototypeC.l _CountGfxModes()
Global CountGfxModes_._CountGfxModes = GetFunction(B3DLibrary, "bbCountGfxModes")
PrototypeC.l _GfxModeWidth(Mode.l)
Global GfxModeWidth_._GfxModeWidth = GetFunction(B3DLibrary, "bbGfxModeWidth")
PrototypeC.l _GfxModeHeight(Mode.l)
Global GfxModeHeight_._GfxModeHeight = GetFunction(B3DLibrary, "bbGfxModeHeight")
PrototypeC.l _GfxModeDepth(Mode.l)
Global GfxModeDepth_._GfxModeDepth = GetFunction(B3DLibrary, "bbGfxModeDepth")
PrototypeC.l _GraphicsWidth()
Global GraphicsWidth_._GraphicsWidth = GetFunction(B3DLibrary, "bbGraphicsWidth")
PrototypeC.l _GraphicsHeight()
Global GraphicsHeight_._GraphicsHeight = GetFunction(B3DLibrary, "bbGraphicsHeight")
PrototypeC.l _GraphicsDepth()
Global GraphicsDepth_._GraphicsDepth = GetFunction(B3DLibrary, "bbGraphicsDepth")
PrototypeC.l _AvailVidMem()
Global AvailVidMem_._AvailVidMem = GetFunction(B3DLibrary, "bbAvailVidMem")
PrototypeC.l _TotalVidMem()
Global TotalVidMem_._TotalVidMem = GetFunction(B3DLibrary, "bbTotalVidMem")
PrototypeC _Graphics(Width.l, Height.l, Depth.l = 0, Mode.l = 0)
Global Graphics_._Graphics = GetFunction(B3DLibrary, "bbGraphics")
PrototypeC.l _FrontBuffer()
Global FrontBuffer_._FrontBuffer = GetFunction(B3DLibrary, "bbFrontBuffer")
PrototypeC.l _BackBuffer()
Global BackBuffer_._BackBuffer = GetFunction(B3DLibrary, "bbBackBuffer")
PrototypeC _EndGraphics()
Global EndGraphics_._EndGraphics = GetFunction(B3DLibrary, "bbEndGraphics")
PrototypeC _ScanLine()
Global ScanLine_._ScanLine = GetFunction(B3DLibrary, "bbScanLine")
PrototypeC _VWait(Flag.l)
Global VWait_._VWait = GetFunction(B3DLibrary, "bbVWait")
PrototypeC _Flip(VWait.l = 1)
Global Flip_._Flip = GetFunction(B3DLibrary, "bbFlip")
PrototypeC _Paint(Window.l)
Global Paint_._Paint = GetFunction(B3DLibrary, "bbPaint")
PrototypeC _SetBuffer(Buffer.l)
Global SetBuffer_._SetBuffer = GetFunction(B3DLibrary, "bbSetBuffer")
PrototypeC.l _GraphicsBuffer()
Global GraphicsBuffer_._GraphicsBuffer = GetFunction(B3DLibrary, "bbGraphicsBuffer")
PrototypeC.l _LoadBuffer(Buffer.l, Filename.p-ascii)
Global LoadBuffer_._LoadBuffer = GetFunction(B3DLibrary, "bbLoadBuffer")
PrototypeC _SaveBuffer(Buffer.l, Filename.p-ascii)
Global SaveBuffer_._SaveBuffer = GetFunction(B3DLibrary, "bbSaveBuffer")
PrototypeC _LockBuffer(Buffer.l)
Global LockBuffer_._LockBuffer = GetFunction(B3DLibrary, "bbLockBuffer")
PrototypeC _UnlockBuffer(Buffer.l)
Global UnlockBuffer_._UnlockBuffer = GetFunction(B3DLibrary, "bbUnlockBuffer")
PrototypeC.l _ReadPixel(x.l, y.l, Buffer.l)
Global ReadPixel_._ReadPixel = GetFunction(B3DLibrary, "bbReadPixel")
PrototypeC _WritePixel(x.l, y.l, Color.l, Buffer.l)
Global WritePixel_._WritePixel = GetFunction(B3DLibrary, "bbWritePixel")
PrototypeC.l _ReadPixelFast(x.l, y.l, Buffer.l)
Global ReadPixelFast_._ReadPixelFast = GetFunction(B3DLibrary, "bbReadPixelFast")
PrototypeC _WritePixelFast(x.l, y.l, Color.l, Buffer.l)
Global WritePixelFast_._WritePixelFast = GetFunction(B3DLibrary, "bbWritePixelFast")
PrototypeC _CopyPixel(SrcX.l, SrcY.l, SrcBuffer.l, DstX.l, DstY.l, Buffer.l)
Global CopyPixel_._CopyPixel = GetFunction(B3DLibrary, "bbCopyPixel")
PrototypeC _CopyPixelFast(SrcX.l, SrcY.l, SrcBuffer.l, DstX.l, DstY.l, Buffer.l)
Global CopyPixelFast_._CopyPixelFast = GetFunction(B3DLibrary, "bbCopyPixelFast")
PrototypeC _Origin(x.l, y.l)
Global Origin_._Origin = GetFunction(B3DLibrary, "bbOrigin")
PrototypeC _Viewport(x.l, y.l, Width.l, Height.l)
Global Viewport_._Viewport = GetFunction(B3DLibrary, "bbViewport")
PrototypeC _Color(Red.l, Green.l, Blue.l)
Global Color_._Color = GetFunction(B3DLibrary, "bbColor")
PrototypeC _ClsColor(Red.l, Green.l, Blue.l)
Global ClsColor_._ClsColor = GetFunction(B3DLibrary, "bbClsColor")
PrototypeC _Cls()
Global Cls_._Cls = GetFunction(B3DLibrary, "bbCls")
PrototypeC _Plot(x.l, y.l)
Global Plot_._Plot = GetFunction(B3DLibrary, "bbPlot")
PrototypeC _Line(x1.l, y1.l, x2.l, y2.l)
Global Line_._Line = GetFunction(B3DLibrary, "bbLine")
PrototypeC _Rect(x.l, y.l, Width.l, Height.l, Solid.l = 1)
Global Rect_._Rect = GetFunction(B3DLibrary, "bbRect")
PrototypeC _Oval(x.l, y.l, Width.l, Height.l, solid.l = 1)
Global Oval_._Oval = GetFunction(B3DLibrary, "bbOval")
PrototypeC _Text(x.l, y.l, Text.p-ascii, CenteredX.l = 0, CenteredY.l = 0)
Global Text_._Text = GetFunction(B3DLibrary, "bbText")
PrototypeC _CopyRect(SrcX.l, SrcY.l, SrcWidth.l, SrcHeight.l, DstX.l, DstY.l, SrcBuffer.l, DstBuffer.l)
Global CopyRect__._CopyRect = GetFunction(B3DLibrary, "bbCopyRect")
PrototypeC _GetColor(x.l, y.l)
Global GetColor_._GetColor = GetFunction(B3DLibrary, "bbGetColor")
PrototypeC _ColorRed()
Global ColorRed_._ColorRed = GetFunction(B3DLibrary, "bbColorRed")
PrototypeC _ColorGreen()
Global ColorGreen_._ColorGreen = GetFunction(B3DLibrary, "bbColorGreen")
PrototypeC _ColorBlue()
Global ColorBlue_._ColorBlue = GetFunction(B3DLibrary, "bbColorBlue")
PrototypeC.l _LoadFont(Name.p-ascii, Height.l = 12, Bold.l = 0, Italic.l = 0, Underline.l = 0)
Global LoadFont_._LoadFont = GetFunction(B3DLibrary, "bbLoadFont")
PrototypeC _FreeFont(Font.l)
Global FreeFont_._FreeFont = GetFunction(B3DLibrary, "bbFreeFont")
PrototypeC _SetFont(Font.l)
Global SetFont_._SetFont = GetFunction(B3DLibrary, "bbSetFont")
PrototypeC.l _FontWidth()
Global FontWidth_._FontWidth = GetFunction(B3DLibrary, "bbFontWidth")
PrototypeC.l _FontHeight()
Global FontHeight_._FontHeight = GetFunction(B3DLibrary, "bbFontHeight")
PrototypeC.l _StringWidth(String.p-ascii)
Global StringWidth_._StringWidth = GetFunction(B3DLibrary, "bbStringWidth")
PrototypeC.l _StringHeight(String.p-ascii)
Global StringHeight_._StringHeight = GetFunction(B3DLibrary, "bbStringHeight")
PrototypeC.l _LoadImage(Filename.p-ascii)
Global LoadImage__._LoadImage = GetFunction(B3DLibrary, "bbLoadImage")
PrototypeC.l _CopyImage(Image.l)
Global CopyImage_._CopyImage = GetFunction(B3DLibrary, "bbCopyImage")
PrototypeC.l _CreateImage(Width.l, Height.l, Frames.l)
Global CreateImage_._CreateImage = GetFunction(B3DLibrary, "bbCreateImage")
PrototypeC.l _LoadAnimImage(Filename.p-ascii, FrameWidth.l, FrameHeight.l, FirstFrame.l, NumFrames.l)
Global LoadAnimImage_._LoadAnimImage = GetFunction(B3DLibrary, "bbLoadAnimImage")
PrototypeC _FreeImage(Image.l)
Global FreeImage_._FreeImage = GetFunction(B3DLibrary, "bbFreeImage")
PrototypeC _SaveImage(Image.l, Filename.p-ascii, Frame.l)
Global SaveImage_._SaveImage = GetFunction(B3DLibrary, "bbSaveImage")
PrototypeC _GrabImage(Image.l, x.l, y.l, Frame.l)
Global GrabImage_._GrabImage = GetFunction(B3DLibrary, "bbGrabImage")
PrototypeC.l _ImageBuffer(Image.l, Frame.l)
Global ImageBuffer_._ImageBuffer = GetFunction(B3DLibrary, "bbImageBuffer")
PrototypeC _DrawImage(Image.l, x.l, y.l, Frame.l = 0)
Global DrawImage_._DrawImage = GetFunction(B3DLibrary, "bbDrawImage")
PrototypeC.l _DrawBlock(Image.l, x.l, y.l, Frame.l)
Global DrawBlock_._DrawBlock = GetFunction(B3DLibrary, "bbDrawBlock")
PrototypeC.l _TileImage(Image.l, x.l, y.l, Frame.l)
Global TileImage_._TileImage = GetFunction(B3DLibrary, "bbTileImage")
PrototypeC.l _TileBlock(Image.l, x.l, y.l, Frame.l)
Global TileBlock_._TileBlock = GetFunction(B3DLibrary, "bbTileBlock")
PrototypeC.l _DrawImageRect(Image.l, x.l, y.l, RectX.l, RectY.l, RectWidth.l, RectHeight.l, Frame.l)
Global DrawImageRect_._DrawImageRect = GetFunction(B3DLibrary, "bbDrawImageRect")
PrototypeC.l _DrawBlockRect(Image.l, x.l, y.l, RectX.l, RectY.l, RectWidth.l, RectHeight.l, Frame.l)
Global DrawBlockRect_._DrawBlockRect = GetFunction(B3DLibrary, "bbDrawBlockRect")
PrototypeC.l _MaskImage(Image.l, Red.l, Green.l, Blue.l)
Global MaskImage_._MaskImage = GetFunction(B3DLibrary, "bbMaskImage")
PrototypeC.l _HandleImage(Image.l, x.l, y.l)
Global HandleImage_._HandleImage = GetFunction(B3DLibrary, "bbHandleImage")
PrototypeC.l _ScaleImage(Image.l, ScaleX.f, ScaleY.f)
Global ScaleImage_._ScaleImage = GetFunction(B3DLibrary, "bbScaleImage")
PrototypeC.l _ResizeImage(Image.l, Width.f, Height.f)
Global ResizeImage_._ResizeImage = GetFunction(B3DLibrary, "bbResizeImage")
PrototypeC.l _RotateImage(Image.l, Angle.f)
Global RotateImage_._RotateImage = GetFunction(B3DLibrary, "bbRotateImage")
PrototypeC.l _TFormImage(Image.l, Xx.f, Xy.f, Yx.f, Yy.f)
Global TFormImage_._TFormImage = GetFunction(B3DLibrary, "bbTFormImage")
PrototypeC.l _TFormFilter(Flag.l)
Global TFormFilter_._TFormFilter = GetFunction(B3DLibrary, "bbTFormFilter")
PrototypeC.l _AutoMidHandle(Flag.l)
Global AutoMidHandle_._AutoMidHandle = GetFunction(B3DLibrary, "bbAutoMidHandle")
PrototypeC.l _MidHandle(Image.l)
Global MidHandle_._MidHandle = GetFunction(B3DLibrary, "bbMidHandle")
PrototypeC.l _ImageWidth(Image.l)
Global ImageWidth_._ImageWidth = GetFunction(B3DLibrary, "bbImageWidth")
PrototypeC.l _ImageHeight(Image.l)
Global ImageHeight_._ImageHeight = GetFunction(B3DLibrary, "bbImageHeight")
PrototypeC.l _ImageXHandle(Image.l)
Global ImageXHandle_._ImageXHandle = GetFunction(B3DLibrary, "bbImageXHandle")
PrototypeC.l _ImageYHandle(Image.l)
Global ImageYHandle_._ImageYHandle = GetFunction(B3DLibrary, "bbImageYHandle")
PrototypeC.l _ImagesOverlap(Image1.l, x1.l, y1.l, Image2.l, x2.l, y2.l)
Global ImagesOverlap_._ImagesOverlap = GetFunction(B3DLibrary, "bbImagesOverlap")
PrototypeC.l _ImagesCollide(Image1.l, x1.l, y1.l, Frame1.l, Image2.l, x2.l, y2.l, Frame2.l)
Global ImagesCollide_._ImagesCollide = GetFunction(B3DLibrary, "bbImagesCollide")
PrototypeC.l _RectsOverlap(x1.l, y1.l, Width1.l, Height1.l, x2.l, y2.l, Width2.l, Height2.l)
Global RectsOverlap_._RectsOverlap = GetFunction(B3DLibrary, "bbRectsOverlap")
PrototypeC.l _ImageRectOverlap(Image.l, x.l, y.l, RectX.l, RectY.l, RectWidth.l, RectHeight.l)
Global ImageRectOverlap_._ImageRectOverlap = GetFunction(B3DLibrary, "bbImageRectOverlap")
PrototypeC.l _ImageRectCollide(Image.l, x.l, y.l, Frame.l, RectX.l, RectY.l, RectWidth.l, RectHeight.l)
Global ImageRectCollide_._ImageRectCollide = GetFunction(B3DLibrary, "bbImageRectCollide")
PrototypeC.l _Write(String.p-ascii)
Global Write_._Write = GetFunction(B3DLibrary, "bbWrite")
PrototypeC.l _Print(String.p-ascii)
Global Print_._Print = GetFunction(B3DLibrary, "bbPrint")
PrototypeC.l _Input(Prompt.p-ascii)
Global Input_._Input = GetFunction(B3DLibrary, "bbInput")
PrototypeC.l _Locate(x.l, y.l)
Global Locate_._Locate = GetFunction(B3DLibrary, "bbLocate")
PrototypeC.l _OpenMovie(Filename.p-ascii)
Global OpenMovie_._OpenMovie = GetFunction(B3DLibrary, "bbOpenMovie")
PrototypeC.l _DrawMovie(Movie.l, x.l, y.l, Width.l, Height.l)
Global DrawMovie_._DrawMovie = GetFunction(B3DLibrary, "bbDrawMovie")
PrototypeC.l _MovieWidth(Movie.l)
Global MovieWidth_._MovieWidth = GetFunction(B3DLibrary, "bbMovieWidth")
PrototypeC.l _MovieHeight(Movie.l)
Global MovieHeight_._MovieHeight = GetFunction(B3DLibrary, "bbMovieHeight")
PrototypeC.l _MoviePlaying(Movie.l)
Global MoviePlaying_._MoviePlaying = GetFunction(B3DLibrary, "bbMoviePlaying")
PrototypeC.l _CloseMovie(Movie.l)
Global CloseMovie_._CloseMovie = GetFunction(B3DLibrary, "bbCloseMovie")
PrototypeC.l _SetGamma(SrcRed.l, SrcGreen.l, SrcBlue.l, DstRed.f, DstGreen.f, DstBlue.f)
Global SetGamma_._SetGamma = GetFunction(B3DLibrary, "bbSetGamma")
PrototypeC.l _UpdateGamma(Calibrate.l)
Global UpdateGamma_._UpdateGamma = GetFunction(B3DLibrary, "bbUpdateGamma")
PrototypeC.f _GammaRed(Gamma.l)
Global GammaRed_._GammaRed = GetFunction(B3DLibrary, "bbGammaRed")
PrototypeC.f _GammaGreen(Gamma.l)
Global GammaGreen_._GammaGreen = GetFunction(B3DLibrary, "bbGammaGreen")
PrototypeC.f _GammaBlue(Gamma.l)
Global GammaBlue_._GammaBlue = GetFunction(B3DLibrary, "bbGammaBlue")
PrototypeC.l _LoaderMatrix(Extension.p-ascii, Xx.f, Xy.f, Xz.f, Yx.f, Yy.f, Yz.f, Zx.f, Zy.f, Zz.f)
Global LoaderMatrix_._LoaderMatrix = GetFunction(B3DLibrary, "bbLoaderMatrix")
PrototypeC.l _HWTexUnits()
Global HWTexUnits_._HWTexUnits = GetFunction(B3DLibrary, "bbHWTexUnits")
PrototypeC.l _HWMultiTex(Flag.l)
Global HWMultiTex_._HWMultiTex = GetFunction(B3DLibrary, "bbHWMultiTex")
PrototypeC.l _WBuffer(Flag.l)
Global WBuffer_._WBuffer = GetFunction(B3DLibrary, "bbWBuffer")
PrototypeC.l _Dither(Flag.l)
Global Dither_._Dither = GetFunction(B3DLibrary, "bbDither")
PrototypeC.l _AntiAlias(Flag.l)
Global AntiAlias_._AntiAlias = GetFunction(B3DLibrary, "bbAntiAlias")
PrototypeC.l _WireFrame(Flag.l)
Global WireFrame_._WireFrame = GetFunction(B3DLibrary, "bbWireFrame")
PrototypeC.l _AmbientLight(Red.f, Green.f, Blue.f)
Global AmbientLight_._AmbientLight = GetFunction(B3DLibrary, "bbAmbientLight")
PrototypeC.l _ClearCollisions()
Global ClearCollisions_._ClearCollisions = GetFunction(B3DLibrary, "bbClearCollisions")
PrototypeC.l _Collisions(SrcType.l, DstType.l, Method.l, Response.l)
Global Collisions_._Collisions = GetFunction(B3DLibrary, "bbCollisions")
PrototypeC.l _UpdateWorld(Elapsed.f = 1.0)
Global UpdateWorld_._UpdateWorld = GetFunction(B3DLibrary, "bbUpdateWorld")
PrototypeC.l _CaptureWorld()
Global CaptureWorld_._CaptureWorld = GetFunction(B3DLibrary, "bbCaptureWorld")
PrototypeC.l _RenderWorld(Tween.f = 1.0)
Global RenderWorld_._RenderWorld = GetFunction(B3DLibrary, "bbRenderWorld")
PrototypeC.l _TrisRendered()
Global TrisRendered_._TrisRendered = GetFunction(B3DLibrary, "bbTrisRendered")
PrototypeC.f _Stats3D(Stats.l)
Global Stats3D_._Stats3D = GetFunction(B3DLibrary, "bbStats3D")
PrototypeC.l _LoadTexture(Filename.p-ascii, Flags.l = 1)
Global LoadTexture_._LoadTexture = GetFunction(B3DLibrary, "bbLoadTexture")
PrototypeC.l _LoadAnimTexture(Filename.p-ascii, Flags.l, FrameWidth.l, FrameHeight.l, FirstFrame.l, NumFrames.l)
Global LoadAnimTexture_._LoadAnimTexture = GetFunction(B3DLibrary, "bbLoadAnimTexture")
PrototypeC.l _CreateTexture(Width.l, Height.l, Flags.l = 3, Frames.l = 1)
Global CreateTexture_._CreateTexture = GetFunction(B3DLibrary, "bbCreateTexture")
PrototypeC.l _FreeTexture(Texture.l)
Global FreeTexture_._FreeTexture = GetFunction(B3DLibrary, "bbFreeTexture")
PrototypeC.l _TextureBlend(Texture.l, Blend.l)
Global TextureBlend_._TextureBlend = GetFunction(B3DLibrary, "bbTextureBlend")
PrototypeC.l _TextureCoords(Texture.l, Flags.l)
Global TextureCoords_._TextureCoords = GetFunction(B3DLibrary, "bbTextureCoords")
PrototypeC.l _ScaleTexture(Texture.l, UScale.f, VScale.f)
Global ScaleTexture_._ScaleTexture = GetFunction(B3DLibrary, "bbScaleTexture")
PrototypeC.l _RotateTexture(Texture.l, Angle.f)
Global RotateTexture_._RotateTexture = GetFunction(B3DLibrary, "bbRotateTexture")
PrototypeC.l _PositionTexture(Texture.l, UPos.f, VPos.f)
Global PositionTexture_._PositionTexture = GetFunction(B3DLibrary, "bbPositionTexture")
PrototypeC.l _TextureWidth(Texture.l)
Global TextureWidth_._TextureWidth = GetFunction(B3DLibrary, "bbTextureWidth")
PrototypeC.l _TextureHeight(Texture.l)
Global TextureHeight_._TextureHeight = GetFunction(B3DLibrary, "bbTextureHeight")
PrototypeC.l _TextureName(Texture.l)
Global TextureName_._TextureName = GetFunction(B3DLibrary, "bbTextureName")
PrototypeC.l _SetCubeFace(Texture.l, Face.l)
Global SetCubeFace_._SetCubeFace = GetFunction(B3DLibrary, "bbSetCubeFace")
PrototypeC.l _SetCubeMode(Texture.l, Mode.l)
Global SetCubeMode_._SetCubeMode = GetFunction(B3DLibrary, "bbSetCubeMode")
PrototypeC.l _TextureBuffer(Texture.l, Frame.l = 0)
Global TextureBuffer_._TextureBuffer = GetFunction(B3DLibrary, "bbTextureBuffer")
PrototypeC.l _ClearTextureFilters()
Global ClearTextureFilters_._ClearTextureFilters = GetFunction(B3DLibrary, "bbClearTextureFilters")
PrototypeC.l _TextureFilter(Extension.p-ascii, Flags.l)
Global TextureFilter_._TextureFilter = GetFunction(B3DLibrary, "bbTextureFilter")
PrototypeC.l _CreateBrush(Red.l = 255, Green.l = 255, Blue.l = 255)
Global CreateBrush_._CreateBrush = GetFunction(B3DLibrary, "bbCreateBrush")
PrototypeC.l _LoadBrush(Filename.p-ascii, Flags.l = 1, UScale.f = 1.0, VScale.f = 1.0)
Global LoadBrush_._LoadBrush = GetFunction(B3DLibrary, "bbLoadBrush")
PrototypeC.l _FreeBrush(Brush.l)
Global FreeBrush_._FreeBrush = GetFunction(B3DLibrary, "bbFreeBrush")
PrototypeC.l _BrushColor(Brush.l, Red.F, Green.F, Blue.F)
Global BrushColor_._BrushColor = GetFunction(B3DLibrary, "bbBrushColor")
PrototypeC.l _BrushAlpha(Brush.l, Alpha.f)
Global BrushAlpha_._BrushAlpha = GetFunction(B3DLibrary, "bbBrushAlpha")
PrototypeC.l _BrushShininess(Brush.l, Value.f)
Global BrushShininess_._BrushShininess = GetFunction(B3DLibrary, "bbBrushShininess")
PrototypeC.l _BrushTexture(Brush.l, Texture.l, Frame.l = 0, Index.l = 0)
Global BrushTexture_._BrushTexture = GetFunction(B3DLibrary, "bbBrushTexture")
PrototypeC.l _GetBrushTexture(Brush.l, Index.l)
Global GetBrushTexture_._GetBrushTexture = GetFunction(B3DLibrary, "bbGetBrushTexture")
PrototypeC.l _BrushBlend(Brush.l, Blend.l)
Global BrushBlend_._BrushBlend = GetFunction(B3DLibrary, "bbBrushBlend")
PrototypeC.l _BrushFX(Brush.l, FX.l)
Global BrushFX_._BrushFX = GetFunction(B3DLibrary, "bbBrushFX")
PrototypeC.l _CreateMesh(Parent.l = 0)
Global CreateMesh_._CreateMesh = GetFunction(B3DLibrary, "bbCreateMesh")
PrototypeC.l _LoadMesh(Filename.p-ascii, Parent.l = 0)
Global LoadMesh_._LoadMesh = GetFunction(B3DLibrary, "bbLoadMesh")
PrototypeC.l _LoadAnimMesh(Filename.p-ascii, Parent.l = 0)
Global LoadAnimMesh_._LoadAnimMesh = GetFunction(B3DLibrary, "bbLoadAnimMesh")
PrototypeC.l _CreateCube(Parent.l = 0)
Global CreateCube_._CreateCube = GetFunction(B3DLibrary, "bbCreateCube")
PrototypeC.l _CreateSphere(Segments.l = 8, Parent.l = 0)
Global CreateSphere_._CreateSphere = GetFunction(B3DLibrary, "bbCreateSphere")
PrototypeC.l _CreateCylinder(Segments.l = 8, Solid.l = 1, Parent.l = 0)
Global CreateCylinder_._CreateCylinder = GetFunction(B3DLibrary, "bbCreateCylinder")
PrototypeC.l _CreateCone(Segments.l = 8, Solid.l = 1, Parent.l = 0)
Global CreateCone_._CreateCone = GetFunction(B3DLibrary, "bbCreateCone")
PrototypeC.l _CopyMesh(Mesh.l, Parent.l = 0)
Global CopyMesh_._CopyMesh = GetFunction(B3DLibrary, "bbCopyMesh")
PrototypeC.l _ScaleMesh(Mesh.l, x.f, y.f, z.f)
Global ScaleMesh_._ScaleMesh = GetFunction(B3DLibrary, "bbScaleMesh")
PrototypeC.l _RotateMesh(Mesh.l, x.f, y.f, z.f)
Global RotateMesh_._RotateMesh = GetFunction(B3DLibrary, "bbRotateMesh")
PrototypeC.l _PositionMesh(Mesh.l, x.f, y.f, z.f)
Global PositionMesh_._PositionMesh = GetFunction(B3DLibrary, "bbPositionMesh")
PrototypeC.l _FitMesh(Mesh.l, x.f, y.f, z.f, Width.f, Height.f, Depth.f, Uniform.l = 0)
Global FitMesh_._FitMesh = GetFunction(B3DLibrary, "bbFitMesh")
PrototypeC.l _FlipMesh(Mesh.l)
Global FlipMesh_._FlipMesh = GetFunction(B3DLibrary, "bbFlipMesh")
PrototypeC.l _PaintMesh(Mesh.l, Brush.l)
Global PaintMesh_._PaintMesh = GetFunction(B3DLibrary, "bbPaintMesh")
PrototypeC.l _AddMesh(Src.l, Dest.l)
Global AddMesh_._AddMesh = GetFunction(B3DLibrary, "bbAddMesh")
PrototypeC.l _UpdateNormals(Mesh.l)
Global UpdateNormals_._UpdateNormals = GetFunction(B3DLibrary, "bbUpdateNormals")
PrototypeC.l _LightMesh(Mesh.l, Red.f, Green.f, Blue.f, Range.f, x.f, y.f, z.f)
Global LightMesh_._LightMesh = GetFunction(B3DLibrary, "bbLightMesh")
PrototypeC.f _MeshWidth(Mesh.l)
Global MeshWidth_._MeshWidth = GetFunction(B3DLibrary, "bbMeshWidth")
PrototypeC.f _MeshHeight(Mesh.l)
Global MeshHeight_._MeshHeight = GetFunction(B3DLibrary, "bbMeshHeight")
PrototypeC.f _MeshDepth(Mesh.l)
Global MeshDepth_._MeshDepth = GetFunction(B3DLibrary, "bbMeshDepth")
PrototypeC.l _MeshesIntersect(SrcMesh.l, DstMesh.l)
Global MeshesIntersect_._MeshesIntersect = GetFunction(B3DLibrary, "bbMeshesIntersect")
PrototypeC.l _CountSurfaces(Mesh.l)
Global CountSurfaces_._CountSurfaces = GetFunction(B3DLibrary, "bbCountSurfaces")
PrototypeC.l _GetSurface(Mesh.l, Index.l)
Global GetSurface_._GetSurface = GetFunction(B3DLibrary, "bbGetSurface")
PrototypeC.l _MeshCullBox(Mesh.l, x.f, y.f, z.f, Width.f, Height.f, Depth.f)
Global MeshCullBox_._MeshCullBox = GetFunction(B3DLibrary, "bbMeshCullBox")
PrototypeC.l _FindSurface(Mesh.l, Brush.l)
Global FindSurface_._FindSurface = GetFunction(B3DLibrary, "bbFindSurface")
PrototypeC.l _CreateSurface(Mesh.l, Brush.l = 0)
Global CreateSurface_._CreateSurface = GetFunction(B3DLibrary, "bbCreateSurface")
PrototypeC.l _GetSurfaceBrush(Surface.l)
Global GetSurfaceBrush_._GetSurfaceBrush = GetFunction(B3DLibrary, "bbGetSurfaceBrush")
PrototypeC.l _GetEntityBrush(Mesh.l)
Global GetEntityBrush_._GetEntityBrush = GetFunction(B3DLibrary, "bbGetEntityBrush")
PrototypeC.l _ClearSurface(Surface.l, Vertices.l = 1, Triangles.l = 1)
Global ClearSurface_._ClearSurface = GetFunction(B3DLibrary, "bbClearSurface")
PrototypeC.l _PaintSurface(Surface.l, Brush)
Global PaintSurface_._PaintSurface = GetFunction(B3DLibrary, "bbPaintSurface")
PrototypeC.l _AddVertex(Surface.l, x.f, y.f, z.f, Tu.f = 0.0, Tv.f = 0.0, Tw.f = 0.0)
Global AddVertex_._AddVertex = GetFunction(B3DLibrary, "bbAddVertex")
PrototypeC.l _AddTriangle(Surface.l, v0.l, v1.l, v2.l)
Global AddTriangle_._AddTriangle = GetFunction(B3DLibrary, "bbAddTriangle")
PrototypeC.l _VertexCoords(Surface.l, Vertex.l, x.f, y.f, z.f)
Global VertexCoords_._VertexCoords = GetFunction(B3DLibrary, "bbVertexCoords")
PrototypeC.l _VertexNormal(Surface.l, Vertex.l, x.f, y.f, z.f)
Global VertexNormal_._VertexNormal = GetFunction(B3DLibrary, "bbVertexNormal")
PrototypeC.l _VertexColor(Surface.l, Vertex.l, Red.f, Green.f, Blue.f, Alpha.f)
Global VertexColor_._VertexColor = GetFunction(B3DLibrary, "bbVertexColor")
PrototypeC.l _VertexTexCoords(Surface.l, Vertex.l, u.f, v.f, w.f, Coords.l)
Global VertexTexCoords_._VertexTexCoords = GetFunction(B3DLibrary, "bbVertexTexCoords")
PrototypeC.l _CountVertices(Surface.l)
Global CountVertices_._CountVertices = GetFunction(B3DLibrary, "bbCountVertices")
PrototypeC.l _CountTriangles(Surface.l)
Global CountTriangles_._CountTriangles = GetFunction(B3DLibrary, "bbCountTriangles")
PrototypeC.f _VertexX(Surface.l, Vertex.l)
Global VertexX_._VertexX = GetFunction(B3DLibrary, "bbVertexX")
PrototypeC.f _VertexY(Surface.l, Vertex.l)
Global VertexY_._VertexY = GetFunction(B3DLibrary, "bbVertexY")
PrototypeC.f _VertexZ(Surface.l, Vertex.l)
Global VertexZ_._VertexZ = GetFunction(B3DLibrary, "bbVertexZ")
PrototypeC.f _VertexNX(Surface.l, Vertex.l)
Global VertexNX_._VertexNX = GetFunction(B3DLibrary, "bbVertexNX")
PrototypeC.f _VertexNY(Surface.l, Vertex.l)
Global VertexNY_._VertexNY = GetFunction(B3DLibrary, "bbVertexNY")
PrototypeC.f _VertexNZ(sSurface.l, Vertex.l)
Global VertexNZ_._VertexNZ = GetFunction(B3DLibrary, "bbVertexNZ")
PrototypeC.f _VertexRed(Surface.l, Vertex.l)
Global VertexRed_._VertexRed = GetFunction(B3DLibrary, "bbVertexRed")
PrototypeC.f _VertexGreen(Surface.l, Vertex.l)
Global VertexGreen_._VertexGreen = GetFunction(B3DLibrary, "bbVertexGreen")
PrototypeC.f _VertexBlue(Surface.l, Vertex.l)
Global VertexBlue_._VertexBlue = GetFunction(B3DLibrary, "bbVertexBlue")
PrototypeC.f _VertexAlpha(Surface.l, Vertex.l)
Global VertexAlpha_._VertexAlpha = GetFunction(B3DLibrary, "bbVertexAlpha")
PrototypeC.f _VertexU(Surface.l, Vertex.l, TexSet.l)
Global VertexU_._VertexU = GetFunction(B3DLibrary, "bbVertexU")
PrototypeC.f _VertexV(Surface.l, Vertex.l, TexSet.l)
Global VertexV_._VertexV = GetFunction(B3DLibrary, "bbVertexV")
PrototypeC.f _VertexW(Surface.l, Vertex.l, TexSet.l)
Global VertexW_._VertexW = GetFunction(B3DLibrary, "bbVertexW")
PrototypeC.l _TriangleVertex(Surface.l, Triangle.l, Vertex.l)
Global TriangleVertex_._TriangleVertex = GetFunction(B3DLibrary, "bbTriangleVertex")
PrototypeC.l _CreateCamera(Parent.l = 0)
Global CreateCamera_._CreateCamera = GetFunction(B3DLibrary, "bbCreateCamera")
PrototypeC.l _CameraZoom(Camera.l, Zoom.f)
Global CameraZoom_._CameraZoom = GetFunction(B3DLibrary, "bbCameraZoom")
PrototypeC.l _CameraRange(Camera.l, ZNear.f, ZFar.f)
Global CameraRange_._CameraRange = GetFunction(B3DLibrary, "bbCameraRange")
PrototypeC.l _CameraClsColor(Camera.l, Red, Green, Blue)
Global CameraClsColor_._CameraClsColor = GetFunction(B3DLibrary, "bbCameraClsColor")
PrototypeC.l _CameraClsMode(Camera.l, ClsColor.l, ClsZbuffer.l)
Global CameraClsMode_._CameraClsMode = GetFunction(B3DLibrary, "bbCameraClsMode")
PrototypeC.l _CameraProjMode(Camera.l, Mode.l)
Global CameraProjMode_._CameraProjMode = GetFunction(B3DLibrary, "bbCameraProjMode")
PrototypeC.l _CameraViewport(Camera.l, x.l, y.l, Width, Height)
Global CameraViewport_._CameraViewport = GetFunction(B3DLibrary, "bbCameraViewport")
PrototypeC.l _CameraFogRange(Camera.l, ZNear.f, ZFar.f)
Global CameraFogRange_._CameraFogRange = GetFunction(B3DLibrary, "bbCameraFogRange")
PrototypeC.l _CameraFogColor(Camera.l, Red, Green, Blue)
Global CameraFogColor_._CameraFogColor = GetFunction(B3DLibrary, "bbCameraFogColor")
PrototypeC.l _CameraFogMode(Camera.l, Mode.l)
Global CameraFogMode_._CameraFogMode = GetFunction(B3DLibrary, "bbCameraFogMode")
PrototypeC.l _CameraProject(Camera.l, x.f, y.f, z.f)
Global CameraProject_._CameraProject = GetFunction(B3DLibrary, "bbCameraProject")
PrototypeC.f _ProjectedX()
Global ProjectedX_._ProjectedX = GetFunction(B3DLibrary, "bbProjectedX")
PrototypeC.f _ProjectedY()
Global ProjectedY_._ProjectedY = GetFunction(B3DLibrary, "bbProjectedY")
PrototypeC.f _ProjectedZ()
Global ProjectedZ_._ProjectedZ = GetFunction(B3DLibrary, "bbProjectedZ")
PrototypeC.l _CameraPick(Camera.l, x.f, y.f)
Global CameraPick_._CameraPick = GetFunction(B3DLibrary, "bbCameraPick")
PrototypeC.l _LinePick(x.f, y.f, z.f, Dx.f, Dy.f, Dz.f, Radius.f)
Global LinePick_._LinePick = GetFunction(B3DLibrary, "bbLinePick")
PrototypeC.l _EntityPick(Entity.l, Range.f)
Global EntityPick_._EntityPick = GetFunction(B3DLibrary, "bbEntityPick")
PrototypeC.l _EntityVisible(SrcEntity.l, DstEntity.l)
Global EntityVisible_._EntityVisible = GetFunction(B3DLibrary, "bbEntityVisible")
PrototypeC.l _EntityInView(Entity.l, Camera.l)
Global EntityInView_._EntityInView = GetFunction(B3DLibrary, "bbEntityInView")
PrototypeC.f _PickedX()
Global PickedX_._PickedX = GetFunction(B3DLibrary, "bbPickedX")
PrototypeC.f _PickedY()
Global PickedY_._PickedY = GetFunction(B3DLibrary, "bbPickedY")
PrototypeC.f _PickedZ()
Global PickedZ_._PickedZ = GetFunction(B3DLibrary, "bbPickedZ")
PrototypeC.f _PickedNX()
Global PickedNX_._PickedNX = GetFunction(B3DLibrary, "bbPickedNX")
PrototypeC.f _PickedNY()
Global PickedNY_._PickedNY = GetFunction(B3DLibrary, "bbPickedNY")
PrototypeC.f _PickedNZ()
Global PickedNZ_._PickedNZ = GetFunction(B3DLibrary, "bbPickedNZ")
PrototypeC.f _PickedTime()
Global PickedTime_._PickedTime = GetFunction(B3DLibrary, "bbPickedTime")
PrototypeC.l _PickedEntity()
Global PickedEntity_._PickedEntity = GetFunction(B3DLibrary, "bbPickedEntity")
PrototypeC.l _PickedSurface()
Global PickedSurface_._PickedSurface = GetFunction(B3DLibrary, "bbPickedSurface")
PrototypeC.l _PickedTriangle()
Global PickedTriangle_._PickedTriangle = GetFunction(B3DLibrary, "bbPickedTriangle")
PrototypeC.l _CreateLight(Type.l = 0, Parent.l = 0)
Global CreateLight_._CreateLight = GetFunction(B3DLibrary, "bbCreateLight")
PrototypeC.l _LightColor(Light.l, Red.F, Green.F, Blue.F)
Global LightColor_._LightColor = GetFunction(B3DLibrary, "bbLightColor")
PrototypeC.l _LightRange(Light.l, Range.f)
Global LightRange_._LightRange = GetFunction(B3DLibrary, "bbLightRange")
PrototypeC.l _LightConeAngles(Light.l, Inner.f, Outer.f)
Global LightConeAngles_._LightConeAngles = GetFunction(B3DLibrary, "bbLightConeAngles")
PrototypeC.l _CreatePivot(Parent.l = 0)
Global CreatePivot_._CreatePivot = GetFunction(B3DLibrary, "bbCreatePivot")
PrototypeC.l _CreateSprite(Parent.l = 0)
Global CreateSprite_._CreateSprite = GetFunction(B3DLibrary, "bbCreateSprite")
PrototypeC.l _LoadSprite(Filename.p-ascii, Flags.l = 1, Parent = 0)
Global LoadSprite_._LoadSprite = GetFunction(B3DLibrary, "bbLoadSprite")
PrototypeC.l _RotateSprite(Sprite.l, Angle.f)
Global RotateSprite_._RotateSprite = GetFunction(B3DLibrary, "bbRotateSprite")
PrototypeC.l _ScaleSprite(Sprite.l, x.f, y.f)
Global ScaleSprite_._ScaleSprite = GetFunction(B3DLibrary, "bbScaleSprite")
PrototypeC.l _HandleSprite(Sprite.l, x.f, y.f)
Global HandleSprite_._HandleSprite = GetFunction(B3DLibrary, "bbHandleSprite")
PrototypeC.l _SpriteViewMode(Sprite.l, Mode.l)
Global SpriteViewMode_._SpriteViewMode = GetFunction(B3DLibrary, "bbSpriteViewMode")
PrototypeC.l _CreateMirror(Parent.l = 0)
Global CreateMirror_._CreateMirror = GetFunction(B3DLibrary, "bbCreateMirror")
PrototypeC.l _CreatePlane(Segments.l = 1, Parent.l = 0)
Global CreatePlane_._CreatePlane = GetFunction(B3DLibrary, "bbCreatePlane")
PrototypeC.l _LoadMD2(Filename.p-ascii, Parent.l = 0)
Global LoadMD2_._LoadMD2 = GetFunction(B3DLibrary, "bbLoadMD2")
PrototypeC.l _AnimateMD2(MD2.l, Mode.l = 1, Speed.f = 1.0, First.l = 0, Last.l = 9999, Transition.f = 0.0)
Global AnimateMD2_._AnimateMD2 = GetFunction(B3DLibrary, "bbAnimateMD2")
PrototypeC.f _MD2AnimTime(MD2.l)
Global MD2AnimTime_._MD2AnimTime = GetFunction(B3DLibrary, "bbMD2AnimTime")
PrototypeC.l _MD2AnimLength(MD2.l)
Global MD2AnimLength_._MD2AnimLength = GetFunction(B3DLibrary, "bbMD2AnimLength")
PrototypeC.l _MD2Animating(MD2.l)
Global MD2Animating_._MD2Animating = GetFunction(B3DLibrary, "bbMD2Animating")
PrototypeC.l _LoadBSP(Filename.p-ascii, Gamma.f, Parent.l = 0)
Global LoadBSP_._LoadBSP = GetFunction(B3DLibrary, "bbLoadBSP")
PrototypeC.l _BSPAmbientLight(BSP.l, Red, Green, Blue)
Global BSPAmbientLight_._BSPAmbientLight = GetFunction(B3DLibrary, "bbBSPAmbientLight")
PrototypeC.l _BSPLighting(BSP.l, Lightmap.l)
Global BSPLighting_._BSPLighting = GetFunction(B3DLibrary, "bbBSPLighting")
PrototypeC.l _CreateTerrain(Grid.l, Parent.l = 0)
Global CreateTerrain_._CreateTerrain = GetFunction(B3DLibrary, "bbCreateTerrain")
PrototypeC.l _LoadTerrain(Filename.p-ascii, Parent.l = 0)
Global LoadTerrain_._LoadTerrain = GetFunction(B3DLibrary, "bbLoadTerrain")
PrototypeC.l _TerrainDetail(Terrain.l, Detail.l, Morphing.l)
Global TerrainDetail_._TerrainDetail = GetFunction(B3DLibrary, "bbTerrainDetail")
PrototypeC.l _TerrainShading(Terrain.l, Flag.l)
Global TerrainShading_._TerrainShading = GetFunction(B3DLibrary, "bbTerrainShading")
PrototypeC.f _TerrainX(Terrain.l, x.f, y.f, z.f)
Global TerrainX_._TerrainX = GetFunction(B3DLibrary, "bbTerrainX")
PrototypeC.f _TerrainY(Terrain.l, x.f, y.f, z.f)
Global TerrainY_._TerrainY = GetFunction(B3DLibrary, "bbTerrainY")
PrototypeC.f _TerrainZ(Terrain.l, x.f, y.f, z.f)
Global TerrainZ_._TerrainZ = GetFunction(B3DLibrary, "bbTerrainZ")
PrototypeC.l _TerrainSize(Terrain.l)
Global TerrainSize_._TerrainSize = GetFunction(B3DLibrary, "bbTerrainSize")
PrototypeC.f _TerrainHeight(Terrain.l, x.l, z.l)
Global TerrainHeight_._TerrainHeight = GetFunction(B3DLibrary, "bbTerrainHeight")
PrototypeC.l _ModifyTerrain(Terrain.l, x.l, z.l, h.f, realtime.l)
Global ModifyTerrain_._ModifyTerrain = GetFunction(B3DLibrary, "bbModifyTerrain")
PrototypeC.l _CreateListener(Parent.l = 0, Rolloff.f = 1.0, Doppler.f = 1.0, Distance.f = 1.0)
Global CreateListener_._CreateListener = GetFunction(B3DLibrary, "bbCreateListener")
PrototypeC.l _EmitSound(Sound.l, Emiter.l)
Global EmitSound_._EmitSound = GetFunction(B3DLibrary, "bbEmitSound")
PrototypeC.l _CopyEntity(Entity.l, Parent.l = 0)
Global CopyEntity_._CopyEntity = GetFunction(B3DLibrary, "bbCopyEntity")
PrototypeC.l _FreeEntity(Entity.l)
Global FreeEntity_._FreeEntity = GetFunction(B3DLibrary, "bbFreeEntity")
PrototypeC.l _HideEntity(Entity.l)
Global HideEntity_._HideEntity = GetFunction(B3DLibrary, "bbHideEntity")
PrototypeC.l _ShowEntity(Entity.l)
Global ShowEntity_._ShowEntity = GetFunction(B3DLibrary, "bbShowEntity")
PrototypeC.l _EntityParent(Entity.l, Parent.l, Glob.l = 1)
Global EntityParent_._EntityParent = GetFunction(B3DLibrary, "bbEntityParent")
PrototypeC.l _CountChildren(Entity.l)
Global CountChildren_._CountChildren = GetFunction(B3DLibrary, "bbCountChildren")
PrototypeC.l _GetChild(Entity.l, Index.l)
Global GetChild_._GetChild = GetFunction(B3DLibrary, "bbGetChild")
PrototypeC.l _FindChild(Entity.l, Name.p-ascii)
Global FindChild_._FindChild = GetFunction(B3DLibrary, "bbFindChild")
PrototypeC.l _LoadAnimSeq(Entity.l, Filename.p-ascii)
Global LoadAnimSeq_._LoadAnimSeq = GetFunction(B3DLibrary, "bbLoadAnimSeq")
PrototypeC.l _SetAnimTime(Entity.l, Time.f, Sequence.l = 0)
Global SetAnimTime_._SetAnimTime = GetFunction(B3DLibrary, "bbSetAnimTime")
PrototypeC.l _Animate(Entity.l, Mode.l = 1, Speed.f = 1.0, Sequence.l = 0, Transition.f = 0.0)
Global Animate_._Animate = GetFunction(B3DLibrary, "bbAnimate")
PrototypeC.l _SetAnimKey(Entity.l, Frame.l, Pos.l = 1, Rot.l = 1, Scale.l = 1)
Global SetAnimKey_._SetAnimKey = GetFunction(B3DLibrary, "bbSetAnimKey")
PrototypeC.l _ExtractAnimSeq(Entity.l, FirstFrame.l, LastFrame.l, Sequence.l)
Global ExtractAnimSeq_._ExtractAnimSeq = GetFunction(B3DLibrary, "bbExtractAnimSeq")
PrototypeC.l _AddAnimSeq(Entity.l, Length.l)
Global AddAnimSeq_._AddAnimSeq = GetFunction(B3DLibrary, "bbAddAnimSeq")
PrototypeC.l _AnimSeq(Entity.l)
Global AnimSeq_._AnimSeq = GetFunction(B3DLibrary, "bbAnimSeq")
PrototypeC.f _AnimTime(Entity.l)
Global AnimTime_._AnimTime = GetFunction(B3DLibrary, "bbAnimTime")
PrototypeC.l _AnimLength(Entity.l)
Global AnimLength_._AnimLength = GetFunction(B3DLibrary, "bbAnimLength")
PrototypeC.l _Animating(Entity.l)
Global Animating_._Animating = GetFunction(B3DLibrary, "bbAnimating")
PrototypeC.l _PaintEntity(Entity.l, Brush.l)
Global PaintEntity_._PaintEntity = GetFunction(B3DLibrary, "bbPaintEntity")
PrototypeC.l _EntityColor(Entity.l, Red.F, Green.F, Blue.F)
Global EntityColor_._EntityColor = GetFunction(B3DLibrary, "bbEntityColor")
PrototypeC.l _EntityAlpha(Entity.l, Alpha.f)
Global EntityAlpha_._EntityAlpha = GetFunction(B3DLibrary, "bbEntityAlpha")
PrototypeC.l _EntityShininess(Entity.l, Value.f)
Global EntityShininess_._EntityShininess = GetFunction(B3DLibrary, "bbEntityShininess")
PrototypeC.l _EntityTexture(Entity.l, Texture.l, Frame.l = 0, Index.l = 0)
Global EntityTexture_._EntityTexture = GetFunction(B3DLibrary, "bbEntityTexture")
PrototypeC.l _EntityBlend(Entity.l, Blend.l)
Global EntityBlend_._EntityBlend = GetFunction(B3DLibrary, "bbEntityBlend")
PrototypeC.l _EntityFX(Entity.l, FX.l)
Global EntityFX_._EntityFX = GetFunction(B3DLibrary, "bbEntityFX")
PrototypeC.l _EntityAutoFade(Entity.l, Near.f, Far.f)
Global EntityAutoFade_._EntityAutoFade = GetFunction(B3DLibrary, "bbEntityAutoFade")
PrototypeC.l _EntityOrder(Entity.l, Value.l)
Global EntityOrder_._EntityOrder = GetFunction(B3DLibrary, "bbEntityOrder")
PrototypeC.f _EntityX(Entity.l, Glob.l = 1)
Global EntityX_._EntityX = GetFunction(B3DLibrary, "bbEntityX")
PrototypeC.f _EntityY(Entity.l, Glob.l = 1)
Global EntityY_._EntityY = GetFunction(B3DLibrary, "bbEntityY")
PrototypeC.f _EntityZ(Entity.l, Glob.l = 1)
Global EntityZ_._EntityZ = GetFunction(B3DLibrary, "bbEntityZ")
PrototypeC.f _EntityPitch(Entity.l, Glob.l = 1)
Global EntityPitch_._EntityPitch = GetFunction(B3DLibrary, "bbEntityPitch")
PrototypeC.f _EntityYaw(Entity.l, Glob.l = 1)
Global EntityYaw_._EntityYaw = GetFunction(B3DLibrary, "bbEntityYaw")
PrototypeC.f _EntityRoll(Entity.l, Glob.l = 1)
Global EntityRoll_._EntityRoll = GetFunction(B3DLibrary, "bbEntityRoll")
PrototypeC.f _GetMatElement(Entity.l, Row.l, Col.l)
Global GetMatElement_._GetMatElement = GetFunction(B3DLibrary, "bbGetMatElement")
PrototypeC.l _TFormPoint(x.f, y.f, z.f, SrcEntity.l, DstEntity.l)
Global TFormPoint_._TFormPoint = GetFunction(B3DLibrary, "bbTFormPoint")
PrototypeC.l _TFormVector(x.f, y.f, z.f, SrcEntity.l, DstEntity.l)
Global TFormVector_._TFormVector = GetFunction(B3DLibrary, "bbTFormVector")
PrototypeC.l _TFormNormal(x.f, y.f, z.f, SrcEntity.l, DstEntity.l)
Global TFormNormal_._TFormNormal = GetFunction(B3DLibrary, "bbTFormNormal")
PrototypeC.f _TFormedX()
Global TFormedX_._TFormedX = GetFunction(B3DLibrary, "bbTFormedX")
PrototypeC.f _TFormedY()
Global TFormedY_._TFormedY = GetFunction(B3DLibrary, "bbTFormedY")
PrototypeC.f _TFormedZ()
Global TFormedZ_._TFormedZ = GetFunction(B3DLibrary, "bbTFormedZ")
PrototypeC.f _VectorYaw(x.f, y.f, z.f)
Global VectorYaw_._VectorYaw = GetFunction(B3DLibrary, "bbVectorYaw")
PrototypeC.f _VectorPitch(x.f, y.f, z.f)
Global VectorPitch_._VectorPitch = GetFunction(B3DLibrary, "bbVectorPitch")
PrototypeC.f _DeltaYaw(SrcEntity.l, DstEntity.l)
Global DeltaYaw_._DeltaYaw = GetFunction(B3DLibrary, "bbDeltaYaw")
PrototypeC.f _DeltaPitch(SrcEntity.l, DstEntity.l)
Global DeltaPitch_._DeltaPitch = GetFunction(B3DLibrary, "bbDeltaPitch")
PrototypeC _ResetEntity(Entity.l)
Global ResetEntity_._ResetEntity = GetFunction(B3DLibrary, "bbResetEntity")
PrototypeC _CaptureEntity(Entity.l)
Global CaptureEntity_._CaptureEntity = GetFunction(B3DLibrary, "bbCaptureEntity")
PrototypeC _EntityType(Entity.l, Type.l, Recursive.l = 0)
Global EntityType_._EntityType = GetFunction(B3DLibrary, "bbEntityType")
PrototypeC _EntityPickMode(Entity.l, Mode.l, Obscurer.l)
Global EntityPickMode_._EntityPickMode = GetFunction(B3DLibrary, "bbEntityPickMode")
PrototypeC.l _GetParent(Entity.l)
Global GetParent_._GetParent = GetFunction(B3DLibrary, "bbGetParent")
PrototypeC.l _GetEntityType(Entity.l)
Global GetEntityType_._GetEntityType = GetFunction(B3DLibrary, "bbGetEntityType")
PrototypeC _EntityRadius(Entity.l, XRadius.f, YRadius.f = 1.0)
Global EntityRadius_._EntityRadius = GetFunction(B3DLibrary, "bbEntityRadius")
PrototypeC _EntityBox(Entity.l, x.f, y.f, z.f, Width.f, Height.f, Depth.f)
Global EntityBox_._EntityBox = GetFunction(B3DLibrary, "bbEntityBox")
PrototypeC.l _EntityCollided(Entity.l, Type.l)
Global EntityCollided_._EntityCollided = GetFunction(B3DLibrary, "bbEntityCollided")
PrototypeC.l _CountCollisions(Entity.l)
Global CountCollisions_._CountCollisions = GetFunction(B3DLibrary, "bbCountCollisions")
PrototypeC.f _CollisionX(Entity.l, Index.l)
Global CollisionX_._CollisionX = GetFunction(B3DLibrary, "bbCollisionX")
PrototypeC.f _CollisionY(Entity.l, Index.l)
Global CollisionY_._CollisionY = GetFunction(B3DLibrary, "bbCollisionY")
PrototypeC.f _CollisionZ(Entity.l, Index.l)
Global CollisionZ_._CollisionZ = GetFunction(B3DLibrary, "bbCollisionZ")
PrototypeC.f _CollisionNX(Entity.l, Index.l)
Global CollisionNX_._CollisionNX = GetFunction(B3DLibrary, "bbCollisionNX")
PrototypeC.f _CollisionNY(Entity.l, Index.l)
Global CollisionNY_._CollisionNY = GetFunction(B3DLibrary, "bbCollisionNY")
PrototypeC.f _CollisionNZ(Entity.l, Index.l)
Global CollisionNZ_._CollisionNZ = GetFunction(B3DLibrary, "bbCollisionNZ")
PrototypeC.f _CollisionTime(Entity.l, Index.l)
Global CollisionTime_._CollisionTime = GetFunction(B3DLibrary, "bbCollisionTime")
PrototypeC.l _CollisionEntity(Entity.l, Index.l)
Global CollisionEntity_._CollisionEntity = GetFunction(B3DLibrary, "bbCollisionEntity")
PrototypeC.l _CollisionSurface(Entity.l, Index.l)
Global CollisionSurface_._CollisionSurface = GetFunction(B3DLibrary, "bbCollisionSurface")
PrototypeC.l _CollisionTriangle(Entity.l, Index.l)
Global CollisionTriangle_._CollisionTriangle = GetFunction(B3DLibrary, "bbCollisionTriangle")
PrototypeC.f _EntityDistance(SrcEntity.l, DstEntity.l)
Global EntityDistance_._EntityDistance = GetFunction(B3DLibrary, "bbEntityDistance")
PrototypeC _MoveEntity(Entity.l, x.f, y.f, z.f)
Global MoveEntity_._MoveEntity = GetFunction(B3DLibrary, "bbMoveEntity")
PrototypeC _TurnEntity(Entity.l, Pitch.f, Yaw.f, Roll.f, Glob.l = 1)
Global TurnEntity_._TurnEntity = GetFunction(B3DLibrary, "bbTurnEntity")
PrototypeC _TranslateEntity(Entity.l, x.f, y.f, z.f, Glob.l = 1)
Global TranslateEntity_._TranslateEntity = GetFunction(B3DLibrary, "bbTranslateEntity")
PrototypeC _PositionEntity(Entity.l, x.f, y.f, z.f, Glob.l = 1)
Global PositionEntity_._PositionEntity = GetFunction(B3DLibrary, "bbPositionEntity")
PrototypeC _ScaleEntity(Entity.l, x.f, y.f, z.f, Glob.l = 1)
Global ScaleEntity_._ScaleEntity = GetFunction(B3DLibrary, "bbScaleEntity")
PrototypeC _RotateEntity(Entity.l, Pitch.f, Yaw.f, Roll.f, Glob.l = 1)
Global RotateEntity_._RotateEntity = GetFunction(B3DLibrary, "bbRotateEntity")
PrototypeC _PointEntity(Entity.l, Target.l, Roll.f = 0)
Global PointEntity_._PointEntity = GetFunction(B3DLibrary, "bbPointEntity")
PrototypeC _AlignToVector(Entity.l, Vx.f, Vy.f, Vz.f, Axis.l, Rate.f)
Global AlignToVector_._AlignToVector = GetFunction(B3DLibrary, "bbAlignToVector")
PrototypeC _NameEntity(Entity.l, Name.p-ascii)
Global NameEntity_._NameEntity = GetFunction(B3DLibrary, "bbNameEntity")
PrototypeC.l _EntityName(Entity.l)
Global _EntityName_._EntityName = GetFunction(B3DLibrary, "bbEntityName")
Macro EntityName_(Entity) : PeekS(_EntityName_(Entity), -1, #PB_Ascii) : EndMacro
PrototypeC _EntityClass(Entity.l)
Global _EntityClass_._EntityClass = GetFunction(B3DLibrary, "bbEntityClass")
Macro EntityClass_(Entity) : PeekS(_EntityClass_(Entity), -1, #PB_Ascii) : EndMacro
PrototypeC _ClearWorld(Entities.l = 1, Brushes.l = 1, Textures.l = 1)
Global ClearWorld_._ClearWorld = GetFunction(B3DLibrary, "bbClearWorld")
PrototypeC _SetEntityID(Entity.l, Id.l)
Global SetEntityID_._SetEntityID = GetFunction(B3DLibrary, "bbSetEntityID")
PrototypeC.l _EntityID(Entity.l)
Global EntityID_._EntityID = GetFunction(B3DLibrary, "bbEntityID")
PrototypeC.l _ActiveTextures()
Global ActiveTextures_._ActiveTextures = GetFunction(B3DLibrary, "bbActiveTextures")
; IDE Options = PureBasic 5.40 LTS (Windows - x86)